version: '3'

services:
  backuppc:
    build: .
    restart: always
    ports:
      - 80:80
    # environment:
    #   - MAILSERVER=
    #   - PORT=
    #   - FROM=
    #   - USER=
    #   - PASSWORD=
    volumes:
      - ./data:/var/lib/BackupPC
      - ./config:/etc/BackupPC

